---
# Case 1.3: The backint agent kit should be extracted from backint agent kit passed as input variable
- name: Get the short name of the provided backup agent package
  set_fact:
    bk_agent_kit_short: "{{ backint_cos_kit | basename }}"
  delegate_to: localhost

- name: Check if the provided backup agent package version is higher equal to {{ minimum_required_vers_backint_ibm_cos }}
  set_fact:
    correct_kit: "{{ backint_cos_kit }}"
  failed_when: ([bk_agent_kit_short, "ge", minimum_required_vers_backint_ibm_cos] | list | compare_versions) == false
  delegate_to: localhost

- name: Check if the directory for backup agent kit exists on target VSI
  stat:
    path: "{{ target_kit_path }}"
  register: exist_status

- name: Create the directory for backup agent kit on target VSI
  file:
    path: "{{ target_kit_path }}"
    state: directory
    recurse: yes
    mode: '0755'
  when: not exist_status.stat.exists

- name: Copy the backup agent kit from {{ backint_agent_path_in_installed_hana_kit }} to {{ target_kit_path }} and unpack it
  unarchive:
    dest: "{{ target_kit_path }}"
    src: "{{ correct_kit }}"
    exclude:
      - python_script_name
      - hdbbackint_file_name
    remote_src: false
...